### ISSUE TITLE
Transporter recall bug 8/13/2018

### ISSUE THREAD

**Issue by ta3370** [DDMers/StarTrek13#51]
During today's new romulan ship test without much information available as to how it happened, the romulan transporter operator managed to use away-team recall to retrieve a fresh-join Starfleet CE from their ship, at the time the romulan ship was in the neutral zone and the starfleet ship was in the starfleet sector.

Summary list: 
https://gyazo.com/69fd88ee65ad8d71d62a4da9db83e529

Discussion leading to summary: 
https://gyazo.com/1bfec47cfcfff856ce57584e6782e377
https://gyazo.com/3927398427e829fe5c5b727ec55d6fd7

Sorry that there isn't more to go off of.

**Comment by Kmc2000** [comment]
Fixed this, retrieve mode is now gone. I'll probably add ability to lock into combadges
