### ISSUE TITLE
Shuttle red alert

### ISSUE THREAD

**Issue by LordWalnut** [DDMers/StarTrek13#59]
[Round ID]: Test server

[Reproduction]: 

![image](https://user-images.githubusercontent.com/25855812/44317887-5156eb80-a42b-11e8-8972-c456c1530816.png)
 

The 'Red Alert' on shuttles look very strange

**Comment by Cdey78** [comment]
Has to do with how shuttle walls were done and how the lighting is placed, no way we can actually fix this unless Kmc wants to change shuttle walls entirely

**Comment by Kmc2000** [comment]
^Cdey, no way to fix it unfortunately, without allowing people to teleport into walls
