### ISSUE TITLE
Constructed Galaxy Class ship missing plasma relays

### ISSUE THREAD

**Issue by Araulius** [DDMers/StarTrek13#80]
[Reproduction]: Start on deep space 9 station, on deep space 9 scenario. Have galaxy class constructed from the stations ship purchasing console. Board the galaxy, and look for the plasma relays all over ship. Find none.

*note: I am not sure if this extends to round start galaxy classes, or galaxy class re-spawns.

**Comment by Kmc2000** [comment]
FIxed recently, I hadn't updated all the ships with the new parts
