### ISSUE TITLE
Resistance is futile is futile! Borg mask button is borked

### ISSUE THREAD

**Issue by Rumiluntti** [DDMers/StarTrek13#81]
[Reproduction]: #Be borg, press button on the top left, assume it plays the soundfile like a sechailer, initiate sadness subroutines as no sound is played.

It can be played by ctrl clicking on the mask itself but the button is broken.

**Comment by Kmc2000** [comment]
Wow this is an old bug coming back

You can alt click it until this is fixed (failsafe)

**Comment by Kmc2000** [comment]
Tested and fixed
