### ISSUE TITLE
Issues on 04/11/18 roundstart time @ 7:27pm GMT+0

### ISSUE THREAD

**Issue by MrSeaside** [DDMers/StarTrek13#84]
[Round ID]: Unknown, roundstart time @ 7:27pm GMT+0 & the following restart

- Autosort from any faction into borg
This process attempts to attach all the individual pieces of borg tech onto the player before they are actually borg, resulting in (what seems to be) the central processor seemingly bouncing off of them and being left on the floor of the borg transporter room during the teleporting around. As expected this breaks the ability to "Message the collective" but the option still appears in the window. I haven't confirmed the absence of central processors in these autobalanced borgs but it's what seemed to be the problem from my perspective.

- Shuttle craft on DS9
Even in it's currently depowered state the shuttle was able to transwarp between sectors without moving from the station once the distortions ceased. This resulted in being able to exit the shuttle and freely spacewalk and in a test of tricorder functions on a borg ship, the transporter tag was able to simultaneously damage the borg ship, beamed them to what on my end was their own
transporter pad according to server text and in practicality, back to DS9. I'm aware this more of a bunch of bugs that probably need untangling but I figured it was important to bring it here.

- Unable to undock from the station
Shuttles powered or otherwise seem unable to leave the station regardless on input. Inputs tested:
Ctrl-click,
Shift-click,
Alt-click
Regular left-click

**Comment by Kmc2000** [comment]
This is weird

The autobalance thing I have no idea about

Finnicky shuttles are also odd, I probably included the wrong check somewhere
