### ISSUE TITLE
Borg Hivemind working while dead

### ISSUE THREAD

**Issue by deadmomo69** [DDMers/StarTrek13#89]
While dead, and in their body, the borg can still communicate in hivemind which allows them to ghost, come back into their body, and metacomm information via the hivemind.

[Reproduction]: Die as a borg, go into your body, and you should still be able to communicate normally using the hivemind feature.

**Comment by Kmc2000** [comment]
OOOOOOF

That's actually a scenario I didn't think of.

I'll patch this
